openapi: "3.0.3"
info:
  title: "JSON API sample"
  description: "A JSON API that allows you to view and add customers"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /ping:
    get:
      description: "Endpoint for pinging the application"
      responses:
        200:
          description: "OK"
          content:
            text/plain:
              schema:
                type: string
              example: "Ping!"
